Inventory item change
UCSolarCarTeam/Solar-Car-Website pull request #147
Opened 2024-01-13 23:04 UTC by justin-phxm

2024-01-20 20:38 UTC, ideen1 commented
Can you please reference which tickets this PR addresses and if there are no tickets what behaviour is changed.

2024-01-20 20:38 UTC, ideen1 requested changes

2024-01-20 20:38 UTC, ideen1 commented on src/app/portal/edit-inventory/edit-inventory.component.html
> +      <!-- <select
Please remove this commented out code

2024-01-29 00:37 UTC, justin-phxm commented
> Can you please reference which tickets this PR addresses and if there are no tickets what behaviour is changed.

This ticket is for fixing the image adding bug
https://uofcsolarcar.atlassian.net/browse/TEL-71?atlOrigin=eyJpIjoiNGVmOGJkYzZmM2JkNGU1ZGEzNzg3M2E2MTQ3Y2NlNGIiLCJwIjoiaiJ9

2024-01-30 04:46 UTC, ideen1 commented
Thanks for updating this. I will take a look this week

2024-02-10 17:24 UTC, ideen1 approved these changes

2024-02-10 17:26 UTC, merged