User/jens varughese/elysia page
UCSolarCarTeam/Solar-Car-Website pull request #22
Opened 2021-01-17 19:48 UTC by JensVarughese

The Elysia Page with a basic implementation of a gallery. The learn more button on the cars page is also linked to the Elysia page.

2021-01-18 06:42 UTC, liconway approved these changes
Lgtm :+1: We'll just need to make sure the Elysia gallery images are higher quality for release.

I'd wait for @JaydenBischoff's approval before merging though

2021-01-18 06:42 UTC, liconway commented on src/app/elysia/elysia.component.css
> +}
If you can put a new line after here, just to appease the Git gods

2021-01-22 01:46 UTC, JaydenBischoff requested changes
Looks really good but I noticed that the pictures in the gallery are really blurry. Were the pictures really small on the original website or could you try resaving and adding the photos to the assets folder.

2021-01-22 01:48 UTC, JensVarughese commented
> Looks really good but I noticed that the pictures in the gallery are really blurry. Were the pictures really small on the original website or could you try resaving and adding the photos to the assets folder.

The pictures on the website were only 100x100 pixels. We could change them when we officially deploy the website.

2021-01-22 01:51 UTC, JaydenBischoff approved these changes
Okay sure we can change them later. Everything else looks good

2021-01-22 02:19 UTC, merged