Add recruitment page
UCSolarCarTeam/Solar-Car-Website pull request #55
Opened 2021-09-01 22:37 UTC by Dillonsd

- Adds a link to the recruitment page to the header
- Adds the recruitment page design as per the Figma design
- Adds links to the Google forms
- Adds a subteam interface (could be beneficial for when the backend is implemented)

**Waiting on the descriptions for the subteam applications**
**Waiting on assets for the page**

2021-09-01 23:00 UTC, JessieG123 requested changes
This picture of Elysia is a bit off screen is that suppose to be like that? 
![image](https://user-images.githubusercontent.com/56773140/131756327-e99c204e-2d3d-472b-aec8-da067e760ee3.png)

2021-09-01 23:04 UTC, Dillonsd commented
> This picture of Elysia is a bit off screen is that suppose to be like that?
> ![image](https://user-images.githubusercontent.com/56773140/131756327-e99c204e-2d3d-472b-aec8-da067e760ee3.png)

That's cz it's a placeholder image.

2021-09-01 23:08 UTC, JessieG123 requested changes
Here's the rest.

Communications: https://forms.gle/w6YJ4akBfVYJ8oGs9 

Multi-team: https://forms.gle/zwn3Tk7Pgf89648a6

2021-09-01 23:13 UTC, JessieG123 reviewed
I think if these are left aligned it might look better or have some space between the text and the edge of the right screen. 
![image](https://user-images.githubusercontent.com/56773140/131757302-4bdbc658-b887-48ee-be22-c553a4a775a5.png)

2021-09-01 23:56 UTC, JessieG123 requested changes
Looks awesome! Just one last thing

Seems to be a lot of white space on the right. Is it possible to decrease it a little so that the text and pic are relatively centered?
![image](https://user-images.githubusercontent.com/56773140/131760187-29144013-020b-43da-a646-dbe02092f639.png)

2021-09-03 01:08 UTC, JaydenBischoff requested changes
Looks great! I have a few things that need to change:

- The info nights are actually the 13th and 16th at 6:30pm
- I didn't anticipate the red and white photo being used. I think it looks nice but I don't like how it says the same thing as the text above. Could you either replace the text at the top with "recruiting now", or replace the image with the other one that I just added to figma, or if you have another idea go for it. 
- Could you also make the image of the car at the top right be bigger/ spread out a bit more
- Last thing, could you change the link on the main page so that it links to this page

Thanks!

2021-09-03 02:26 UTC, JessieG123 requested changes
Looks great! 

Just one thing, on a bigger screen the Recruiting Now is at the very edge of the screen. If it's not too much maybe add some space?
![image](https://user-images.githubusercontent.com/56773140/131941061-c5f9f797-4f5f-448d-bd65-d92a92c9c28f.png)

2021-09-03 02:29 UTC, JessieG123 requested changes

2021-09-03 02:29 UTC, JessieG123 commented on src/app/business/recruitment/recruitment.component.html
> +                September 17, 2021<br />
Should be September 16 for the second info night.

2021-09-03 02:39 UTC, Dillonsd commented
> Looks great!
> 
> Just one thing, on a bigger screen the Recruiting Now is at the very edge of the screen. If it's not too much maybe add some space?
> ![image](https://user-images.githubusercontent.com/56773140/131941061-c5f9f797-4f5f-448d-bd65-d92a92c9c28f.png)

Hm, what size screen is this? There should be padding

2021-09-03 03:22 UTC, JaydenBischoff commented
Hmm the text seems to get cut off for me. Maybe make it a bit smaller or put the text and picture in a grid container.
![image](https://user-images.githubusercontent.com/44730154/131945783-ae3cd7c4-6f56-4a6f-be16-b5f60eb2e848.png)

2021-09-03 17:15 UTC, JessieG123 commented
> > Looks great!
> > Just one thing, on a bigger screen the Recruiting Now is at the very edge of the screen. If it's not too much maybe add some space?
> > ![image](https://user-images.githubusercontent.com/56773140/131941061-c5f9f797-4f5f-448d-bd65-d92a92c9c28f.png)
> 
> Hm, what size screen is this? There should be padding

1920 x 1080

2021-09-04 01:06 UTC, JessieG123 approved these changes
Excellent. Looks good!

2021-09-04 18:43 UTC, JaydenBischoff approved these changes
I'm still seeing the text issue but it's a bit better. Lets merge it for now and look into fixing it as another task.

2021-09-05 01:20 UTC, merged